name: DetailingShop
favicon: null
layout_spectrum: 0.9073271916713566
typography_spectrum: 0.5059798660222441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a7ebd'
    - '#000000'
    - '#c2146d'
    - '#d5bf15'
  brandStrength: 0
  lightness: 0.030382476281374693
  saturation: 0.6875
  rhythmicContrast: 0.93361526587978
purpose: []
