name: DetailingShop
favicon: null
layout_spectrum: 0.9073271916713566
typography_spectrum: 0.5059798660222441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7731022720690817
  lightness: 0.030382476281374693
  saturation: 0.353854653891176
  rhythmicContrast: 0.93361526587978
purpose: []
